# Generated by Django 6.0 on 2025-12-20 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
