# Generated by Django 6.0 on 2025-12-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['criado_em']},
        ),
    ]
